[package]
authors      = ["Your Name <your.email@example.com>"]
description  = "SWC plugin for transforming import declarations"
edition      = "2021"
name         = "swc_plugin_import_replacer"
repository   = "https://github.com/yourusername/transform-import-declaration-plugin"
rust-version = "1.79"
version      = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
heck       = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
swc_core   = { workspace = true, features = ["ecma_plugin_transform"] }
